### PR TITLE
Added Contact me form

### LINKED ISSUE #6: adding a contact me form
I think a contact me form would be nice feature to add. You can let me know where you want to add it if you consider it

### PR DESCRIPTION
**Pull request by sakshii00**
I haven't added the form yet on the page since I wasn't sure where to add it. You can tell me based on your preference. 

closes #6 
The preview of the form component is below:-
Screenshot 2024-10-09 023104

I haven't added any actions yet but the form can mail to your own gmail or something similar.

### CODE REVIEW

**Comment by kingsmen732** [comment]
We would like this feature in another tile just like email , github button in the current website. look into it and you can have people to support in this regard. I will assign people who are interested in the same feature kindly coordinate and discuss with them so you can assign some part of work which they can help you with. ☺️

**Comment by sakshii00** [comment]
@kingsmen732 a tile that says contact me sounds alright? You can send me image of how you would like it and I would implement it in that.

**Comment by kingsmen732** [comment]
You can be creative in this case , just stick to the stable and bit formal styles

**Comment by sakshii00** [comment]
Alright @kingsmen732

**Comment by sakshii00** [comment]
Hello, i added the tile as requested. Here is the preview:-

image

When the tile is clicked:-

image


 I added the form with reference to how the project section comes up.

**Comment by kingsmen732** [comment]
i like quality code you have given , where are we collecting this form details ? like is it linked to formspark or any other form collecting service? please mention that in code so ill merge this PR 🔥

**Comment by sakshii00** [comment]
There is no backend for the form right now.. you can tell me what you prefer and I will implement it that way. We can use self-email too where the details of the form will be emailed to own email. @kingsmen732

**Comment by kingsmen732** [comment]
> There is no backend for the form right now.. you can tell me what you prefer and I will implement it that way. We can use self-email too where the details of the form will be emailed to own email. @kingsmen732

I actually prefer the email method you suggested me , we can implement that one only . if you want to make a separate service which does you can use formspark which has its own form id which is linked to a basket which collects all the details and sends as a email to our user. i hope formspark will be helpful for you in mere future projects but for now we will implement email only.
kuddos to your immediate response 🔥🫡

**Comment by sakshii00** [comment]
Would node-mailer be okay for implementing this? @kingsmen732 
And thank you

**Comment by kingsmen732** [comment]
> Would node-mailer be okay for implementing this? @kingsmen732 And thank you

i am not sure about node-mailer as we are exposing a mail for simply mailing us with no control over unique entries in it , adding to it deployment will have some aftermath over it as smtp port needs to open in vercel backend . kindly check once if it is deployment ready if not use formspark its quite easy. @sakshii00

**Comment by sakshii00** [comment]
@kingsmen732  The email would be in environmental variable ofcourse but I think I will checkout formspark and let you know.

**Comment by sakshii00** [comment]
@kingsmen732 I have added formspark. I tested it too and it is working fine. Please review it.

**Comment by sakshii00** [comment]
@kingsmen732 Please review this.

**Comment by kingsmen732** [comment]
> @kingsmen732 Please review this.

Kindly check the review to be made, i have created @sakshii00

**Comment by sakshii00** [comment]
@kingsmen732 I am sorry, I can't see it. I added formspark as we last discussed.

**Comment by sakshii00** [comment]
@kingsmen732 is the environmental variable needed or not? I added it since the form id shouldn't be revealed

**Review by kingsmen732 — APPROVED** [review]

**Comment by kingsmen732** [comment]
> @kingsmen732 is the environmental variable needed or not? I added it since the form id shouldn't be revealed

The entire repo is meant to be in private when in deployment so i don't think so we are using env , having all necessary changes to be made in profileconfig file alone makes it easier to edit for the user at any instance. @sakshii00

**Comment by sakshii00** [comment]
@kingsmen732 i added the id in profileconfig.

**Pull request merged**
